name: Murlok.io parser

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run app
      run: python main_export.py
      env: 
        BNET_CLIENT_ID: ${{ secrets.BNET_CLIENT_ID }}
        BNET_CLIENT_SECRET: ${{ secrets.BNET_CLIENT_SECRET }}
    - name: rm pycache
      run: rm -rf __pycache__
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'MurlokExport.zip'
        directory: ..
        path: MurlokExport
        recursive_exclusions: '*.git* *.py'
    - name: set env
      run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV     
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.NOW }}
        files: MurlokExport.zip
    - name: "Upload to CurseForge"
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "MurlokExport.zip"
        display_name: "MurlokExport v${{ env.NOW }}"
        game_endpoint: "wow"
        game_versions: "11.1.7"
        project_id: "1273867"
        changelog: ${{ github.event.workflow_run.head_commit.message }}
        token: "${{ secrets.CF_API_TOKEN }}"    