name: Murlok.io parser

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Export Murlok.io data
      run: python Python/main_export.py
      env: 
        BNET_CLIENT_ID: ${{ secrets.BNET_CLIENT_ID }}
        BNET_CLIENT_SECRET: ${{ secrets.BNET_CLIENT_SECRET }}
    - name: Remove python cache
      run: rm -rf Python/__pycache__
    - name: Set environment variable NOW for versioning
      run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        filename: MurlokExport_v${{ env.NOW }}.zip
        directory: ..
        path: MurlokExport
        exclusions: "*.git*"
        recursive_exclusions: "*.py"
    - name: Move ZIP file
      run: mv ../MurlokExport_v${{ env.NOW }}.zip .
    - name: Set environment variable CHANGELOG
      run: echo "CHANGELOG='$(cat Changelog.md)'" >> $GITHUB_ENV
    - name: Upload to CurseForge
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: MurlokExport_v${{ env.NOW }}.zip
        display_name: MurlokExport_v${{ env.NOW }}
        game_endpoint: wow
        game_versions: "11.1.7"
        project_id: "1273867"
        changelog: ${{ env.CHANGELOG }}
        token: ${{ secrets.CF_API_TOKEN }}