name: Murlok.io parser

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: PROD
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run app
      run: python main_export.py
      env: 
        BNET_TOKEN: ${{ secrets.BNET_TOKEN }}
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'MurlokExport.zip'
        exclusions: '*.git* *.py __pycache__'
    - name: set env
      run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV     
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.NOW }}
        files: MurlokExport.zip